FROM alpine:3.19

RUN apk add --no-cache \
    iptables \
    iproute2 \
    iputils \
    bash

COPY scripts/start_router.sh /start.sh
RUN sed -i 's/\r$//' /start.sh && chmod +x /start.sh

ENTRYPOINT ["/start.sh"]
